apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-nftlb
  namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kube-nftlb-rbac
subjects:
  - kind: ServiceAccount
    name: kube-nftlb
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
