apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-nftlb
  namespace: kube-system
spec:
  selector:
      matchLabels:
        name: kube-nftlb
  template:
    metadata:
      labels:
        name: kube-nftlb
    spec:
      hostNetwork: true
      containers:
      - name: daemon
        image: daemon
        imagePullPolicy: Never
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
      - name: client
        image: client
        imagePullPolicy: Never
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
